#!/bin/sh
APPDIR=`dirname $0`;
GWTDIR=/home/lucasw/other/gwt-linux-1.3.3;
java  -cp "$APPDIR/src:$APPDIR/bin:$GWTDIR/gwt-user.jar:$GWTDIR/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" binarymillenium.tiles.Tiles/tiles.html;
